import { Box, Heading, SimpleGrid, Stack } from '@chakra-ui/react'
import * as React from 'react'
import { BiDirections, BiHappyBeaming } from 'react-icons/bi'
import { FaGraduationCap, FaRegLifeRing } from 'react-icons/fa'
import { FeaturesCTAButton } from './FeaturesCTAButton'
import { Feature } from './Feature'
import { Testimonial } from './Testimonial'

export const Features = () => {
  return (
    <Box as="section" pb="24">
      <Box bg="gray.800" color="white" pt="24" pb="12rem">
        <Box
          maxW={{
            base: 'xl',
            md: '7xl',
          }}
          mx="auto"
          px={{
            base: '6',
            md: '8',
          }}
        >
          <Stack
            spacing="10"
            direction={{
              base: 'column',
              lg: 'row',
            }}
            align={{
              base: 'flex-start',
              lg: 'center',
            }}
            justify="space-between"
          >
            <Heading
              size="2xl"
              lineHeight="short"
              fontWeight="extrabold"
              maxW={{
                base: 'unset',
                lg: '800px',
              }}
            >
              Impermanent loss protection
            </Heading>
            <FeaturesCTAButton
              w={{
                base: 'full',
                md: 'auto',
              }}
            >
              Read more
            </FeaturesCTAButton>
          </Stack>
          <SimpleGrid
            columns={{
              base: 1,
              md: 2,
              lg: 4,
            }}
            spacing={{
              base: '12',
              md: '8',
              lg: '2',
            }}
            mt={{
              base: '12',
              md: '20',
            }}
          >
            <Feature icon={<BiDirections />} title="Borrowers">
              When a borrower decides to exit the system, and their account is in healthy state, they are entitled to receive compensation for any impermanent loss experienced, denominated in HAP token. The amounts are escrowed by the protocol and can be vested over a period of time.
            </Feature>
            <Feature icon={<BiHappyBeaming />} title="Stakers">
              Stakers play a central role in the protocol as they provide the pool of liquidity which absorbs the effects of I/L generated by borrowers. As such, they are entitled to staking rewards as well as to a portion (30%) of the token swap fees generated by the borrowers‘ liquidity positions.
            </Feature>
            <Feature icon={<FaGraduationCap />} title="LP Bonds">
              The LP bond mechanism serves an important function as it provides a way for stakers to pay their debt at a discounted rate and the same time, enables the protocol to control and own its own liquidity. 
            </Feature>
            <Feature icon={<FaRegLifeRing />} title="Rewards and Fees">
              The liquidity positions which borrowers engage with generate a substantial amount of revenues in terms of token swap fees and they are shared across users of the protocols. Borrowers get 70% of the fees generated by token exchanges, while stakers receive the remaining 30%. 
            </Feature>
          </SimpleGrid>
        </Box>
      </Box>
      <Box mt="-24">
        <Box
          maxW={{
            base: 'xl',
            md: '7xl',
          }}
          mx="auto"
          px={{
            base: '6',
            md: '8',
          }}
        >
          <SimpleGrid
            spacing="14"
            columns={{
              base: 1,
              lg: 2,
            }}
          >
            {/* <Testimonial
              image="https://images.unsplash.com/photo-1600486913747-55e5470d6f40?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80"
              name="Alvina Tores"
              role="CEO, Chakra Group"
            >
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
              exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </Testimonial>
            <Testimonial
              image="https://images.unsplash.com/photo-1589729482945-ca6f3a235f7a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80"
              name="Jessie Jones"
              role="Marketing Manager"
            >
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
              exercitation ullamco.
            </Testimonial> */}
          </SimpleGrid>
        </Box>
      </Box>
    </Box>
  )
}

export default Features;